### ISSUE TITLE
rows.go bug :UTF8characters ORA-01406: fetched column value was truncated

### ISSUE THREAD

**Issue by robinsoon** [jzaikovs/ora#1]
NEW CASE:       os.Setenv("NLS_LANG", "AMERICAN_AMERICA.AL32UTF8")

go  run  (Query Next) panic  :
TRACE:rows.go:30: OCIStmtFetch2(...) -> ORA-01406: fetched column value was truncated

A Chinese character
Go  UTF8  : 3 Byte      <->      in Oracle ZHS16GBK：2Byte

There is not enough space to store Chinese characters after encoding, which leads to the length of out-of-column.

Reference  ：github.com\mattn\go-oci8
```
result := C.OCIStmtFetch2(
		rows.stmt.stmt,
		rows.stmt.conn.errHandle,
		1,
		C.OCI_FETCH_NEXT,
		0,
		C.OCI_DEFAULT)
```

```
// CGoStringN coverts C OraText to Go string
func cGoStringN(s *C.OraText, size int) string {
	if size == 0 {
		return ""
	}
	p := (*[1 << 30]byte)(unsafe.Pointer(s))
	buf := make([]byte, size)
	copy(buf, p[:])
	return *(*string)(unsafe.Pointer(&buf))
}


```
This is working correctly ，But I don't want to use Cgo。

**Comment by robinsoon** [comment]
Test example：anyColumn in Oracle  type  VARCHAR2(100) 
Value = "注射用盐酸头孢替安,注射用盐酸头孢替安,注射用盐酸头孢替安,,注射用盐酸头孢替安"

Oracle ENV: set nls_lang=SIMPLIFIED CHINESE_CHINA.ZHS16GBK


```
CREATE TABLE TCHARSCASE(
A100  Varchar2(100)
) ;

INSERT INTO TCHARSCASE(A100) VALUES("注射用盐酸头孢替安,注射用盐酸头孢替安,注射用盐酸头孢替安,,注射用盐酸头孢替安") ;
commit;
SELECT A100 , length(A100 )  FROM  TCHARSCASE  ;

```
length  result:         40   


Go script   BEFORE CONNECT:
```
os.Setenv("NLS_LANG", "AMERICAN_AMERICA.AL32UTF8") 
........some code
//Query
rows, err := db.Query("SELECT A100 , length( A100 )  FROM  TCHARSCASE where rownum<=1")
for rows.Next() {
      rows.Scan(colsdata...)
....
```
(Run View Results)

Provide developers with the above debugging information, hopefully useful.

**Comment by jzaikovs** [comment]
Problem is that oracle doesn't return correct data size needed to store encoded text, fixed by doubling allocated buffer.

**Comment by robinsoon** [comment]
> Problem is that oracle doesn't return correct data size needed to store encoded text, fixed by doubling allocated buffer.

### **Exactly right. Thank you very much for your support. Good luck！**
